import {
    SiReact,
    SiNextdotjs,
    SiTypescript,
    SiTailwindcss,
    SiNodedotjs,
    SiMongodb,
    SiExpress,
    SiPrisma,
    SiMysql,
    SiSass,
} from "react-icons/si";
import { Project } from "./types";

export const projects: Project[] = [
    {
        id: "1",
        year: 2025,
        title: "E-commerce Platform",
        description: "Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.Uma plataforma completa de e-commerce com sistema de pagamentos, carrinho de compras, autenticação de usuários e painel administrativo. Desenvolvido com foco em performance e experiência do usuário.",
        quote: "Transformando a experiência de compra online com tecnologia moderna",
        techStack: [
            { name: "Next.js", icon: SiNextdotjs },
            { name: "TypeScript", icon: SiTypescript },
            { name: "Tailwind CSS", icon: SiTailwindcss },
            { name: "Prisma", icon: SiPrisma },
            { name: "MongoDB", icon: SiMongodb },
        ],
        githubUrl: "https://github.com/th0mzzz/ecommerce",
        liveUrl: "https://ecommerce-demo.vercel.app",
        category: "fullstack",
        image: "",
        featured: true,
    },
    {
        id: "2",
        year: 2025,
        title: "Dashboard Analytics",
        description: "Dashboard interativo para visualização de dados e métricas em tempo real. Inclui gráficos dinâmicos, filtros avançados e exportação de relatórios.",
        quote: "Dados complexos, visualização simples",
        techStack: [
            { name: "React", icon: SiReact },
            { name: "TypeScript", icon: SiTypescript },
            { name: "Tailwind CSS", icon: SiTailwindcss },
            { name: "Node.js", icon: SiNodedotjs },
        ],
        githubUrl: "https://github.com/th0mzzz/dashboard",
        liveUrl: "https://dashboard-demo.vercel.app",
        category: "frontend",
        featured: true,
    },
    {
        id: "3",
        year: 2024,
        title: "API RESTful",
        description: "API robusta e escalável para gerenciamento de recursos com autenticação JWT, rate limiting, documentação Swagger e testes automatizados.",
        quote: "Backend sólido, aplicações confiáveis",
        techStack: [
            { name: "Node.js", icon: SiNodedotjs },
            { name: "Express", icon: SiExpress },
            { name: "TypeScript", icon: SiTypescript },
            { name: "MySQL", icon: SiMysql },
            { name: "Prisma", icon: SiPrisma },
        ],
        githubUrl: "https://github.com/th0mzzz/api-rest",
        category: "backend",
    },
    {
        id: "4",
        year: 2024,
        title: "Landing Page Corporativa",
        description: "Landing page moderna e responsiva para empresa de tecnologia. Design minimalista com animações suaves e otimização para SEO.",
        quote: "Primeira impressão que converte",
        techStack: [
            { name: "Next.js", icon: SiNextdotjs },
            { name: "TypeScript", icon: SiTypescript },
            { name: "Sass", icon: SiSass },
        ],
        githubUrl: "https://github.com/th0mzzz/landing-corp",
        liveUrl: "https://landing-corp.vercel.app",
        category: "frontend",
    },
    {
        id: "5",
        year: 2024,
        title: "Task Manager App",
        description: "Aplicação fullstack para gerenciamento de tarefas com drag-and-drop, colaboração em tempo real e notificações push.",
        quote: "Organize suas tarefas, conquiste seus objetivos",
        techStack: [
            { name: "React", icon: SiReact },
            { name: "Node.js", icon: SiNodedotjs },
            { name: "MongoDB", icon: SiMongodb },
            { name: "Tailwind CSS", icon: SiTailwindcss },
        ],
        githubUrl: "https://github.com/th0mzzz/task-manager",
        liveUrl: "https://task-manager-demo.vercel.app",
        category: "fullstack",
    },
    {
        id: "6",
        year: 2023,
        title: "Portfolio Website",
        description: "Website de portfólio pessoal com design único, animações fluidas e seções interativas para apresentação de projetos e skills.",
        quote: "Mostrando quem sou através do código",
        techStack: [
            { name: "Next.js", icon: SiNextdotjs },
            { name: "TypeScript", icon: SiTypescript },
            { name: "Tailwind CSS", icon: SiTailwindcss },
        ],
        githubUrl: "https://github.com/th0mzzz/portfolio",
        liveUrl: "https://th0mzzz.dev",
        category: "frontend",
        featured: true,
    },
];

export const categories = [
    { key: "all", label: "All" },
    { key: "frontend", label: "Frontend" },
    { key: "fullstack", label: "Fullstack" },
    { key: "backend", label: "Backend" },
];

