import { JourneyItem, JourneyTab } from "./types";

export const journeyTabs: JourneyTab[] = [
  { key: "all", label: "All" },
  { key: "work", label: "Work Experience" },
  { key: "education", label: "Education" },
];

export const journeyItems: JourneyItem[] = [
  {
    id: "1",
    category: "work",
    title: "IT Advisor - Web Developer",
    organization: "Jandira City Hall",
    organizationLogo: "",
    startDate: "02/2025",
    endDate: "Now",
    description:
      "I'm currently working as an IT Advisor/Web Developer at Jandira's City Hall, providing technical support to various departments and developing web applications that improve internal processes and public services.",
    skills: [
      "React",
      "Figma",
      "TypeScript",
      "Node.js",
      "Fastify",
      "Tailwind CSS",
      "Bootstrap",
      "PHP",
      "MySQL",
      "Github",
      "Git",
      "Linux",
      "Swagger",
    ],
  },
  {
    id: "2",
    category: "work",
    title: "Internship - Web Developer",
    organization: "Jandira City Hall",
    organizationLogo: "",
    startDate: "07/2023",
    endDate: "12/2024",
    description:
      "Internship focused on web development, building internal web applications and providing technical support to various departments.",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "PHP",
      "MySQL",
      "Git",
      "Bootstrap",
      "Figma",
    ],
  },
  {
    id: "3",
    category: "education",
    title: "Information for Internet Technical Course",
    organization: "FIEBTECH",
    organizationLogo: "",
    startDate: "01/2022",
    endDate: "12/2024",
    description:
      "An Technical course focused on software development, covering programming fundamentals, database management, web development, and software engineering principles.",
    skills: [
      "JavaScript",
      "Node.JS",
      "MySQL",
      "Git",
      "EJS",
      "Bootstrap",
      "Figma",
      "Adobe Illustrator",
      "Adobe Photoshop",
    ],
  },
  {
    id: "4",
    category: "education",
    title: "Software Engineering",
    organization: "FIAP",
    startDate: "01/2025",
    endDate: "12/2028",
    description:
      "A Bachelor's degree program in Software Engineering, covering software development methodologies, programming languages, database management, and software architecture.",
    skills: [
      "Scrum",
      "Figma",
      "JavaScript",
      "React",
      "Node.js",
      "Database Design",
      "MySQL",
      "Domain Drive Design",
      "Java",
      "Git",
      "Arduino",
      "C++",
      "VR modeling",
      "Python",
      "Dinamic Programming",
    ],
  },
  {
    id: "5",
    category: "education",
    title: "English Course",
    organization: "Wizard",
    startDate: "09/2023",
    endDate: "09/2026",
    description:
      "An intensive English course focused on improving communication skills, including listening, speaking, reading, and writing.",
    skills: [
      "English",
      "Communication",
      "Listening",
      "Speaking",
      "Reading",
      "Writing",
    ],
  },
];
